version: "3.7"

x-yarp-head: &yarp-head
  image: icubteamcode/superbuild-icubhead:v2022.05.2_sources
  environment:
    - YARP_FORWARD_LOG_ENABLE=1
    - YARP_ROBOT_NAME
  volumes:
    - "${HOME}/${YARP_CONF_PATH}:/root/.config/yarp"
    - "/dev:/dev"
    - "/usr/local/src/robot/robots-configuration/iCubGenova11:/root/iCubGenova11"
  ports:
    - "10000:10000"
  network_mode: "host"
  privileged: true


services:

  yrobotinterface:
    <<: *yarp-head
    command: sh -c "if [ -f "/root/.config/yarp/yarp_namespace.conf" ]; then yarp wait $$(echo $$(cat /root/.config/yarp/yarp_namespace.conf)); else yarp wait /root; fi; cd /root/iCubGenova11; yarprobotinterface"


