version: "3.7"

x-icub-test: &icub-test
  image: icubteamcode/superbuild-icubtest:master-unstable_sources
  environment:
    - DISPLAY=${DISPLAY}
    - QT_X11_NO_MITSHM=1
    - XAUTHORITY=/root/.Xauthority
    - YARP_FORWARD_LOG_ENABLE=1
    - YARP_ROBOT_NAME
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix"
    - "${XAUTHORITY}:/root/.Xauthority"
    - "${HOME}/${YARP_CONF_PATH}:/root/.config/yarp"
    - "${HOME}/icub-test_results:/projects/robotology-superbuild/src/icub-tests/suites/results:rw"
  network_mode: "host"
  privileged: true
  #ipc: host


services:

  ylogger:
    <<: *icub-test
    command: sh -c "if [ -f "/root/.config/yarp/yarp_namespace.conf" ]; then yarp wait $$(echo $$(cat /root/.config/yarp/yarp_namespace.conf)); else yarp wait /root; fi; yarplogger --start"

  test-suite:
    <<: *icub-test
    command: sh -c "cd projects/robotology-superbuild/src/icub-tests/suites && robottestingframework-testrunner -v -t OpticalEncodersDrift.so -p "--robot ""icub"" --part ""left_arm"" --joints ""(2)"" --home ""(0)"" --speed ""(20)"" --max ""(10)"" --min ""(-10)"" --cycles 100 --tolerance 1.0 "
